$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  genome_fa:
    type: string

  rmsk_out:
    type: string

  gencode_gtf:
    type: string

  txomes:
    type: object
    patternProperties:
      "^.*txome$":
        type: object
        properties:
          te_subfamilies:
            type: array
            items:
              type: string
          chrs:
            type: array
            items:
              type: string
          simulations:
            type: object
            patternProperties:
              "^.*$":
                type: object
                properties:
                  tx:
                    type: string
                    patternProperties:
                      "uniform_sim|gtex_sim":
                  te:
                    type: string
                    patternProperties:
                      "single_intergenic_l1hs":
                  strand_specific:
                    type: boolean
                  readlen:
                    type: integer
                  nsamples:
                    type: integer
                  paired:
                    type: boolean
                required:
                  - tx
                  - te
                  - strand_specific
                  - readlen
                  - nsamples
          illumina_samplesheet:
            type: string
          ont_samplesheet:
            type: string

required:
  - genome_fa
  - rmsk_out
  - gencode_gtf
  - txomes
