$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  genome_fa:
    type: string

  rmsk_out:
    type: string

  gencode_gtf:
    type: string

  txomes:
    type: object
    patternProperties:
      "^.*txome$":
        type: object
        properties:
          rmsk_query:
            type: string
          chrs:
            type: array
            items:
              type: string
          simulations:
            type: object
            patternPproperties:
              "uniform_sim|gtex_sim|test_sim":
                type: object
                properties:
                  te_sim:
                    type: array
                    items:
                      type: string
                  readlen:
                    type: integer
                  strand_specific:
                    type: boolean
                  counts:
                    type: string
                required:
                  - te_sim
                  - strand_specific
                  - readlen
        required:
          - rmsk_query
          - chrs
          - simulations

required:
  - genome_fa
  - rmsk_out
  - gencode_gtf
  - txomes
