channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - pyranges
  - bedtools>=2.30.0
  - gffread>=0.12.7
  - r-essentials>=4.1
  - r-devtools
  - r-argparser
  - r-biocmanager
  - bioconductor-fishpond
  - ipykernel
  - biopython
  - mygene
  - pip
  - tqdm
  - black
  - tree
  - git>=2
  - git-lfs>=2.2.1
  - pip:
    - git+https://github.com/mikecuoco/myutils.git
