# configuration for snakemake workflow

# reference files to use
genome_fa: "ftp://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz"
rmsk_out: "ftp://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.out.gz"
gencode_gtf: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_26/gencode.v26.basic.annotation.gtf.gz"

# list of transcriptomes generate and simulate reads from
txomes:
  chr22_l1hs_txome:
    rmsk_query: "repName == 'L1HS' & length > 6000"
    chrs:
      - "chr22"
    simulations:
      gtex_sim:
        te_sim:
          - "single_intergenic_l1hs"
        strand_specific: True
        readlen: 100
        gtex_counts: resources/GTEx/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct
        gtex_metadata: resources/GTEx/annotations_v8_GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt
