# configuration for snakemake workflow

# reference files to use
genome_fa: "resources/hg38.fa.gz"
rmsk_out: "resources/hg38.fa.out.gz"
gencode_gtf: "resources/gencode.v26.annotation.gtf.gz"

# list of transcriptomes generate and simulate reads from COPIED FROM TEST DATA FOR CLARITY
txomes:
  test_txome:
    chrs:
      - "chr22"
    te_subfamilies:
      - "L1HS"
    full_length: False
    simulations:
      test:
        tx: uniform_sim
        te: single_intergenic_l1hs
        nsamples: 1
        strand_specific: True
        readlen: 100

    ont_samplesheet: ont_samplesheet.tsv
    illumina_samplesheet: illumina_samplesheet.tsv
