# configuration for snakemake workflow

# reference files to use
genome_fa: resources/gencode.v26.annotation.gtf.gz
rmsk_out: ngs-test-data/scrnaseq_10x_v3/ref/rmsk_chr22.out
gencode_gtf: resources/hg38.fa.gz

# list of transcriptomes generate and simulate reads from
txomes:
  test_txome:
    chrs:
      - "chr22"
    te_subfamilies:
      - "L1HS"
    full_length: False
    simulations:
      test:
        tx: uniform_sim
        te: single_intergenic_l1hs
        nsamples: 1
        strand_specific: True
        readlen: 100

    ont_samplesheet: ont_samplesheet.tsv
    illumina_samplesheet: illumina_samplesheet.tsv
