# configuration for snakemake workflow

# reference files to use
genome_fa: ngs-test-data/rnaseq/ref/genome.chr22.fa
rmsk_out: ngs-test-data/scrnaseq_10x_v3/ref/rmsk_chr22.out
gencode_gtf: ngs-test-data/rnaseq/ref/txome.chr22.gtf

# list of transcriptomes generate and simulate reads from
txomes:
  test_txome:
    rmsk_query: "repName == 'L1HS' & length > 6000"
    chrs:
      - "chr22"
    simulations:
      test_sim:
        te_sim:
          - "single_intergenic_l1hs"
        strand_specific: True
        readlen: 100
    ont_samplesheet: ont_samplesheet.tsv
    illumina_samplesheet: illumina_samplesheet.tsv
